name: Run Required Checks
run-name: PR Checks for ${{ github.ref_name }}

# Trigger jobs whenever Trunk Merge Queue tests a PR using a `trunk-merge/` branch
on:
  push:
    branches:
      - trunk-merge/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved', '*/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run TESTS
        run: swift test --use-integrated-swift-driver
  swift-regression-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ["5.9", "5.10"]
    container: swift:${{ matrix.swift-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: rm Package.resolved && swift build

  apple-platform-regression-tests:
    runs-on: macos-15
    strategy:
      matrix:
        destination:
        - "platform=macOS,arch=arm64"
        - "platform=macOS,arch=arm64,variant=Mac Catalyst"
        - "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5"
        - "platform=iOS Simulator,name=iPad mini (A17 Pro),OS=18.2"
        - "platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=18.5"
        - "platform=visionOS Simulator,name=Apple Vision Pro,OS=2.5"
        - "platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm),OS=11.5"
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test for ${{ matrix.destination }}
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme Afluent-Package \
            -destination '${{ matrix.destination }}' \
            clean build