name: Release

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Generate DocC Static Site
        run: |
            swift package --allow-writing-to-directory ./docs \
              generate-documentation --target Afluent \
              --disable-indexing \
              --transform-for-static-hosting \
              --hosting-base-path Afluent/ \
              --include-extended-types \
              --output-path ./docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./docs
 