name: Release

on:
  release:
    types: [ created ]
  pull_request:

jobs:
  release-afluent:
    uses: ./.github/workflows/docc-release.yml
    with:
      targets: ${{ 'Afluent,AfluentTesting' }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
