name: Release

on:
  release:
    types: [ created ]
  pull_request:

jobs:
  release-afluent:
    uses: ./.github/workflows/docc-release.yml
    with:
      target: ${{ 'Afluent' }}
  release-afluent-testing:
    uses: ./.github/workflows/docc-release.yml
    with:
      target: ${{ 'AfluentTesting' }}
 