# name: Release

# on:
#   release:
#     types: [ created ]

# jobs:
#   release:
#     runs-on: macos-13
#     steps:
#       - uses: actions/checkout@v2
#       - name: Generate DocC Static Site
#         run: |
#             swift package --allow-writing-to-directory ./docs \
#               generate-documentation --target Afluent \
#               --disable-indexing \
#               --transform-for-static-hosting \
#               --hosting-base-path Afluent/ \
#               --output-path ./docs
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./docs
 