name: Release

on:
  release:
    types: [ created ]
  pull_request:

jobs:
  release:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Generate DocC Static Site
        run: |
            swift package --allow-writing-to-directory ./docs-temp \
              generate-documentation \
              --target Afluent \
              --target AfluentTesting \
              --disable-indexing \
              --transform-for-static-hosting \
              --hosting-base-path Afluent/ \
              --include-extended-types \
              --source-service github \
              --source-service-base-url https://github.com/Tyler-Keith-Thompson/Afluent/blob/main \
              --checkout-path "$(pwd)" \
              --output-path ./docs-temp
            mkdir ./docs
            echo "<html></html>" > ./docs/index.html
            rsync --recursive ./docs-temp/Afluent.doccarchive ./docs/Afluent
            rsync --recursive ./docs-temp/AfluentTesting.doccarchive ./docs/AfluentTesting
            rm -rf ./docs-temp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs